import React from 'react'
import Productscoverimage from './Productscoverimage'
import Productsdetailssection from './Productsdetailssection'
import '../Productsstyle.css'
import { useState } from 'react'
import image1 from '../updatedimages/cpu.jpeg'
import image2 from '../updatedimages/gpu.jpeg'
import image3 from '../updatedimages/ssd.jpeg'
import image4 from '../updatedimages/hdd.jpeg'

const Products = () => {
  const [items,Setitems]=useState(
    [ {id:1,title:'Central Processing Unit (CPU)',content:"The CPU, or Central Processing Unit, is the brain of your computer, responsible for executing instructions and performing calculations that drive all your applications and processes. This high-performance CPU features advanced architecture with multiple cores and high clock speeds, ensuring exceptional speed and responsiveness. Designed for both gaming enthusiasts and professionals, it handles intensive tasks like video editing, 3D rendering, and complex computations with ease. Equipped with advanced thermal management technology, it maintains optimal performance without overheating, while its energy-efficient design reduces power consumption. The CPU's ability to manage multiple threads simultaneously enhances multitasking capabilities, allowing for seamless transitions between demanding applications. Whether you’re upgrading an existing system or building a new one, this CPU provides the power and reliability needed for a smooth computing experience. With support for the latest technologies and future-proof performance, it’s a solid choice for those seeking top-tier processing power and efficiency in their work and entertainment setups.",image:image1},
      {id:2,title:"Graphical Processing Unit (GPU)",content:"The GPU, or Graphics Processing Unit, is essential for rendering high-quality graphics and accelerating complex visual computations. Designed for both gamers and professionals, this GPU boasts exceptional performance with high core counts and fast memory, enabling smooth, detailed visuals and fluid frame rates in demanding games and applications. Its advanced architecture supports real-time ray tracing, AI-enhanced graphics, and high-resolution textures, providing an immersive experience in both virtual and augmented reality environments. Equipped with efficient cooling solutions, it maintains peak performance even under heavy loads, reducing thermal throttling and ensuring longevity. The GPU also features support for multi-monitor setups and high-definition displays, enhancing productivity and gaming experiences. With robust driver support and compatibility with the latest software, it integrates seamlessly into various systems, from high-end gaming rigs to professional workstations. Whether you’re editing videos, designing 3D models, or enjoying the latest games, this GPU delivers the power and reliability needed for exceptional visual performance and overall system responsiveness.",image:image2},
      {id:3,title:"Solid State Drive(SSD)",content:"The SSD (Solid State Drive) represents a significant upgrade from traditional hard drives, offering superior speed, reliability, and efficiency. With no moving parts, the SSD uses flash memory to store data, resulting in faster boot times, quicker file transfers, and enhanced overall system responsiveness. This SSD boasts high read and write speeds, making it ideal for demanding applications such as video editing, gaming, and large file management. Its compact design ensures easy installation in various devices, from laptops to desktops. Additionally, the SSD's durability and shock resistance provide reliable performance even in mobile or high-vibration environments. With improved energy efficiency compared to mechanical drives, it helps extend battery life in portable devices. The SSD also features advanced data protection technologies, safeguarding your important files against corruption and loss. Whether you're upgrading your current system or building a new one, this SSD delivers a noticeable performance boost and a more responsive computing experience. It's an excellent choice for those seeking speed, reliability, and efficiency in their storage solutions.",image:image3},
      {id:4,title:"Hard Disk Drive (HDD)",content:"The HDD (Hard Disk Drive) is a traditional storage solution known for its high capacity and cost-effectiveness. Utilizing magnetic storage technology, it offers substantial storage space at a lower price compared to SSDs, making it ideal for bulk data storage and archival needs. This HDD features a large capacity, allowing you to store vast amounts of files, documents, videos, and software without worrying about running out of space. It’s suitable for applications where speed is less critical, such as file backups, media libraries, and large-scale data storage. While it may not match the speed of SSDs in terms of boot times and file transfer rates, it provides reliable and consistent performance for everyday tasks. The HDD’s mechanical design includes spinning disks and read/write heads, which can handle high-capacity storage requirements efficiently. Its affordability and ample storage make it a valuable addition to any system, whether as a primary drive for data or as an additional drive for expanded storage needs.",image:image4}])
  return (
    <div>
      <Productscoverimage/>
      <Productsdetailssection items={items}/>
    </div>
  )
}

export default Products
